config/routes.rb
Rails.application.routes.draw do
  resources :wizards

end

app/models/wizard.rb
class Wizard < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/wizards_controller.rb
class WizardsController < ApplicationController
  before_action :set_wizard, only: [:show, :edit, :update, :destroy]

  # GET /wizards
  # GET /wizards.json
  def index
    @wizards = Wizard.all
  end

  # GET /wizards/1
  # GET /wizards/1.json
  def show
  end

  # GET /wizards/new
  def new
    @wizard = Wizard.new
  end

  # GET /wizards/1/edit
  def edit
  end

  # POST /wizards
  # POST /wizards.json
  def create
    @wizard = Wizard.new(wizard_params)

    respond_to do |format|
      if @wizard.save
        format.html { redirect_to @wizard, notice: 'Wizard was successfully created.' }
        format.json { render :show, status: :created, location: @wizard }
      else
        format.html { render :new }
        format.json { render json: @wizard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wizards/1
  # PATCH/PUT /wizards/1.json
  def update
    respond_to do |format|
      if @wizard.update(wizard_params)
        format.html { redirect_to @wizard, notice: 'Wizard was successfully updated.' }
        format.json { render :show, status: :ok, location: @wizard }
      else
        format.html { render :edit }
        format.json { render json: @wizard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wizards/1
  # DELETE /wizards/1.json
  def destroy
    @wizard.destroy
    respond_to do |format|
      format.html { redirect_to wizards_url, notice: 'Wizard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wizard
      @wizard = Wizard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wizard_params
      params.require(:wizard).permit(:name, :color, :height, :is_good)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wizards_helper.rb
module WizardsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Quizwhiz</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/wizards/_form.html.erb
<%= form_for(@wizard) do |f| %>
  <% if @wizard.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wizard.errors.count, "error") %> prohibited this wizard from being saved:</h2>

      <ul>
      <% @wizard.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.number_field :height %>
  </div>
  <div class="field">
    <%= f.label :is_good %><br>
    <%= f.check_box :is_good %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/wizards/edit.html.erb
<h1>Editing Wizard</h1>

<%= render 'form' %>

<%= link_to 'Show', @wizard %> |
<%= link_to 'Back', wizards_path %>

app/views/wizards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Wizards</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Color</th>
      <th>Height</th>
      <th>Is good</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wizards.each do |wizard| %>
      <tr>
        <td><%= wizard.name %></td>
        <td><%= wizard.color %></td>
        <td><%= wizard.height %></td>
        <td><%= wizard.is_good %></td>
        <td><%= link_to 'Show', wizard %></td>
        <td><%= link_to 'Edit', edit_wizard_path(wizard) %></td>
        <td><%= link_to 'Destroy', wizard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wizard', new_wizard_path %>

app/views/wizards/new.html.erb
<h1>New Wizard</h1>

<%= render 'form' %>

<%= link_to 'Back', wizards_path %>

app/views/wizards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wizard.name %>
</p>

<p>
  <strong>Color:</strong>
  <%= @wizard.color %>
</p>

<p>
  <strong>Height:</strong>
  <%= @wizard.height %>
</p>

<p>
  <strong>Is good:</strong>
  <%= @wizard.is_good %>
</p>

<%= link_to 'Edit', edit_wizard_path(@wizard) %> |
<%= link_to 'Back', wizards_path %>